<?php
  $__type = $type ?? 'button';
  $__tag = $__type === 'link' ? 'a' : 'button';
  $__attributes = $this->htmlAttributes($attributes ?? []);
  $__attributes['type'] = $__type;
  if (!isset($title) && !isset($label) && isset($ariaLabel)) {
    $__attributes['aria-label'] = $ariaLabel;
  }
  if (isset($ariaCurrent)) {
    $__attributes['aria-current'] = $ariaCurrent;
  }
  $values = [];
  if (isset($iconClass)) {
    $values['iconClass'] = $iconClass;
  }
  if (isset($title)) {
    $values['title'] = $title;
  }
  if (isset($label)) {
    $values['label'] = $label;
  }
?>
<<?= $__tag ?><?= $__attributes->add('class', 'finna-btn') ?>><?=
  $this->render('components/molecules/icons/finna-icon-label/finna-icon-label.phtml', $values);
?></<?= $__tag ?>>
