<?php
  $attributes = $attributes ?? [];
  $attributes['class'] = (array)($attributes['class'] ?? []);
  $attributes['class'][] = 'finna-nav';
  $attributes['class'][] = 'nav';
?>
<ul<?= $this->attributes($attributes) ?>>
  <?php foreach ($items as $item): ?>
    <?php if (isset($renderChildren)) $item['renderChildren'] = $renderChildren; ?>
    <?= $this->render('components/molecules/navigation/finna-nav-item/finna-nav-item.phtml', $item); ?>
  <?php endforeach; ?>
</ul>
