<?php
  $tabsNavClasses = ['hidden-xs'];
  $navbarClasses = ['visible-xs'];
  if (!empty($additionalClasses)) {
    if (strpos($additionalClasses, 'finna-multi-level-nav-lg') !== false) {
      $tabsNavClasses[] = 'finna-tabs-nav-lg';
    }
    if (strpos($additionalClasses, 'finna-multi-level-nav-content') !== false) {
      $navbarClasses[] = 'finna-navbar-content';
    }
  }
?>
<div class="finna-multi-level-nav <?= $additionalClasses ?? '' ?>">
  <?= $this->render('components/organisms/navigation/finna-tabs-nav/finna-tabs-nav.phtml', [
      'additionalClasses' => implode(' ', $tabsNavClasses),
      'ariaLabel' => $ariaLabel,
      'items' => $items,
    ]); ?>
  <?= $this->render('components/organisms/navigation/finna-navbar/finna-navbar.phtml', [
      'additionalClasses' => implode(' ', $navbarClasses),
      'ariaLabel' => $ariaLabel,
      'brandContent' => $brandContent ?? $activeLabel ?? '',
      'brandLink' => $brandLink ?? null,
      'brandSrOnly' => $brandSrOnly ?? null,
      'collapseContent' => $this->render('components/molecules/navigation/finna-nav/finna-nav.phtml', [
          'additionalClasses' => 'navbar-nav',
          'items' => $items
        ]),
      'collapseId' => $collapseId,
      'toggleBtnIconClass' => $toggleBtnIconClass ?? 'fa-handle-open',
      'toggleBtnLabel' => $toggleBtnLabel ?? null,
      'toggleBtnSrOnly' => $toggleBtnSrOnly ?? null
    ]); ?>
</div>
