<?php
  $navTabsClasses = ['hidden-xs'];
  $navbarClasses = ['visible-xs'];
  if (!empty($additionalClasses)) {
    if (strpos($additionalClasses, 'finna-multi-level-nav-lg') !== false) {
      $navTabsClasses[] = 'finna-nav-tabs-lg';
    }
    if (strpos($additionalClasses, 'finna-multi-level-nav-content') !== false) {
      $navbarClasses[] = 'finna-navbar-content';
    }
  }
  $tabsPrimary = [];
  foreach ($items as $item) {
    if (isset($item['active']) && boolval($item['active'])) {
      $activeLabel = $item['label'];
      if (!empty($item['children'])) {
        $tabsSecondary = $item['children'];
        foreach ($tabsSecondary as $secondaryItem) {
          if (isset($secondaryItem['active']) && boolval($secondaryItem['active'])) {
            $activeLabel = $secondaryItem['label'];
          }
        }
      }
    }
    unset($item['children']);
    $tabsPrimary[] = $item;
  }
?>
<div class="finna-multi-level-nav <?= $additionalClasses ?? '' ?>">
  <?= $this->render('components/molecules/navigation/finna-nav-tabs/finna-nav-tabs.phtml', [
      'additionalClasses' => implode(' ', $navTabsClasses),
      'ariaLabel' => (empty($tabsSecondary) ? $ariaLabel: $ariaLabelPrimary),
      'tabs' => $tabsPrimary,
    ]); ?>
  <?php if (!empty($tabsSecondary)): ?>
    <?= $this->render('components/molecules/navigation/finna-nav-tabs/finna-nav-tabs.phtml', [
        'additionalClasses' => 'finna-nav-tabs-secondary ' . implode(' ', $navTabsClasses),
        'ariaLabel' => $ariaLabelSecondary,
        'tabs' => $tabsSecondary,
      ]); ?>
  <?php endif; ?>
  <?= $this->render('components/organisms/navigation/finna-navbar/finna-navbar.phtml', [
      'additionalClasses' => implode(' ', $navbarClasses),
      'ariaLabel' => $ariaLabel,
      'brandContent' => $brandContent ?? $activeLabel ?? '',
      'brandLink' => $brandLink ?? null,
      'brandSrOnly' => $brandSrOnly ?? null,
      'collapseContent' => $this->render('components/molecules/navigation/finna-nav/finna-nav.phtml', [
          'additionalClasses' => 'navbar-nav',
          'items' => $items
        ]),
      'collapseId' => $collapseId,
      'toggleBtnIconClass' => $toggleBtnIconClass ?? 'fa-handle-open',
      'toggleBtnLabel' => $toggleBtnLabel ?? null,
      'toggleBtnSrOnly' => $toggleBtnSrOnly ?? null
    ]); ?>
</div>
