<?php
  $active = isset($active) ? (boolval($active) ? 'true' : 'false') : 'false';
  $classes = [];
  if (!empty($children)) {
    $classes[] = 'dropdown';
    if ($active == 'true') {
      $classes[] = 'open';
    }
  } elseif ($active == 'true') {
    $classes[] = 'active';
  }
?>
<li<?php if (!empty($id)): ?> id="<?= $id ?>"<?php endif; ?>
  <?php if (!empty($classes)): ?> class="<?= implode(' ', $classes) ?>"<?php endif; ?>
  <?php if (empty($children)): ?> aria-selected="<?= $active ?>"<?php endif; ?>>
  <?php if (empty($children)): ?>
    <a href="<?= $link ?? '#' ?>"><?= $label ?></a>
    <?php if (!empty($tooltipBtn)): ?>
      <?= $this->render('components/molecules/tooltips/finna-tooltip-btn/finna-tooltip-btn.phtml', $tooltipBtn) ?>
    <?php endif; ?>
  <?php else: ?>
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
      aria-expanded="<?= $active ?>"><?= $label ?> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <?php foreach ($children as $child): ?>
        <li><a href="<?= $child['link'] ?>"><?= $child['label'] ?></a></li>
      <?php endforeach; ?>
    </ul>
  <?php endif; ?>
</li>
