<?php
  $attributes = $this->attributes($attributes ?? []);
  $renderChildren = $renderChildren ?? 'dropdown';
  if (!empty($children) && 'dropdown' === $renderChildren) {
    $attributes->add('class', 'dropdown');
  }
  elseif (isset($active) ? boolval($active) : false) {
    $attributes->add('class', 'active');
    $attributes['aria-current'] = 'page';
  }

  // Process child attributes if necessary.
  if (!empty($children) && 'false' !== $renderChildren) {
    foreach ($children as $i => $child) {
      $childAttributes = $this->attributes($child['attributes'] ?? []);
      if (isset($child['active']) ? boolval($child['active']) : false) {
        $attributes->add('class', 'active-trail');
        $childAttributes->add('class', 'active');
        $childAttributes['aria-current'] = 'page';
      }
      if ($hasDescription = !empty($child['description'])) {
        $childAttributes->add('class', 'nav-item-has-description');
      }
      $child['attributes'] = $childAttributes;
      $linkAttributes = $this->attributes($child['linkAttributes'] ?? []);
      $linkAttributes['href'] = $child['link'];
      $child['linkAttributes'] = $linkAttributes;
      $children[$i] = $child;
    }
  }
?>
<li<?= $attributes ?>>
  <?php if (!empty($children) && 'dropdown' === $renderChildren): ?>
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
      aria-expanded="false"><?= $label ?> <b class="caret"></b></a>
  <?php else: ?>
    <a href="<?= $link ?>"<?php if (!empty($target)): ?> target="<?= $target ?>"<?php endif; ?>><?= $label ?></a>
    <?php if (!empty($tooltipBtn)): ?>
      <?= $this->render('components/molecules/tooltips/finna-tooltip-btn/finna-tooltip-btn.phtml', $tooltipBtn) ?>
    <?php endif; ?>
  <?php endif; ?>
  <?php if (!empty($children) && 'false' !== $renderChildren): ?>
    <ul<?php if ('simple' !== $renderChildren): ?> class="dropdown-menu"<?php endif; ?>>
      <?php foreach ($children as $child): ?>
        <li<?= $child['attributes'] ?>>
          <a<?= $child['linkAttributes'] ?>><span><?= $child['label'] ?></span>
          <?php if ($hasDescription): ?><span role="note"><?= $child['description'] ?></span><?php endif; ?></a>
        </li>
      <?php endforeach; ?>
    </ul>
  <?php endif; ?>
</li>
