<h6>Button - Button with label</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $attributes,
    'iconClass' => null,
    'label' => $label,
    'tooltip' => null,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Link with label</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $__linkAttributes,
    'iconClass' => null,
    'label' => $label,
    'tooltip' => null,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Button with icon and label</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $attributes,
    'iconClass' => $iconClass,
    'label' => $label,
    'tooltip' => null,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Link with icon and label</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $__linkAttributes,
    'iconClass' => $iconClass,
    'label' => $label,
    'tooltip' => null,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Button with icon, label and tooltip</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $attributes,
    'iconClass' => $iconClass,
    'label' => $label,
    'tooltip' => $tooltip,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Disabled button with icon, label and tooltip</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $__disabledButtonAttributes,
    'iconClass' => $iconClass,
    'label' => $label,
    'tooltip' => $tooltip,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Link with icon, label and tooltip</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $__linkAttributes,
    'iconClass' => $iconClass,
    'label' => $label,
    'tooltip' => $tooltip,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Button with icon and accessibility label</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => $a11yLabel,
    'attributes' => $attributes,
    'iconClass' => $iconClass,
    'label' => null,
    'tooltip' => null,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Link with icon and accessibility label</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => $a11yLabel,
    'attributes' => $__linkAttributes,
    'iconClass' => $iconClass,
    'label' => null,
    'tooltip' => null,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Button with icon and tooltip</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $attributes,
    'iconClass' => $iconClass,
    'label' => null,
    'tooltip' => $tooltip,
    'type' => null,
  ]); ?>

<h6 class="mt-5">Button - Link with icon and tooltip</h6>

<?= $this->render('components/molecules/buttons/finna-btn', [
    'ariaCurrent' => null,
    'a11yLabel' => null,
    'attributes' => $__linkAttributes,
    'iconClass' => $iconClass,
    'label' => null,
    'tooltip' => $tooltip,
    'type' => null,
  ]); ?>
