<?= $this->render('components/organisms/navigation/finna-multi-level-nav/finna-multi-level-nav.phtml',
  [
    'additionalClasses' => 'finna-multi-level-nav-content finna-multi-level-nav-lg',
    'ariaLabel' => 'Ohjenavigaatio',
    'ariaLabelPrimary' => 'Ohjenavigaatio taso 1',
    'ariaLabelSecondary' => 'Ohjenavigaatio taso 2',
    'collapseId' => 'nav-help-collapse',
    'items' => [
      [
        'active' => true,
        'children' => [
          [
            'active' => true,
            'label' => 'Haun pikaohje',
            'link' => '#',
          ],
          [
            'label' => 'Perushaun ohje',
            'link' => '#',
          ],
          [
            'label' => 'Tarkennetun haun ohje',
            'link' => '#',
          ],
        ],
        'label' => 'Hakuohjeet',
      ],
      [
        'children' => [
          [
            'label' => 'Neuvoja kirjautumiseen',
            'link' => '#',
          ],
          [
            'label' => 'Oman tilin hallinta',
            'link' => '#',
          ],
        ],
        'label' => 'Kirjautuminen ja oma tili',
      ],
      [
        'label' => 'Suosikkilistat',
        'link' => '#',
      ],
      [
        'label' => 'Aineistojen käyttö',
        'children' => [
          [
            'label' => 'Aineistojen käyttö',
            'link' => '#',
          ],
          [
            'label' => 'CC-lisenssit',
            'link' => '#',
          ],
        ]
      ],
      [
        'label' => 'Video-ohjeet',
        'children' => [
          [
            'label' => 'Haun tekeminen Finna.fi:ssä',
            'link' => '#',
          ],
          [
            'label' => 'Suosikkilistojen luonti',
            'link' => '#',
          ],
          [
            'label' => 'Kirjautuminen ja oma tilin hallinta',
            'link' => '#',
          ],
          [
            'label' => 'Kirjastokortin liittäminen Finna-tiliin',
            'link' => '#',
          ],
        ]
      ],
    ],
    'toggleBtnLabel' => 'Lisää'
  ]
);
