<?php
  $attributes = $this->htmlAttributes($attributes ?? []);
  $attributes->set([
    'type' => 'button',
    'data-toggle' => 'tooltip',
    'data-html' => 'true',
    'data-placement' => $placement ?? 'bottom',
    'data-original-title' => $content ?? ''
  ]);
  if (!isset($label) && isset($ariaLabel)) {
    $attributes['aria-label'] = $ariaLabel;
  }
?>
<button<?= $attributes->add('class', 'finna-tooltip-btn') ?>>
  <?php if (isset($iconClass)): ?><i class="<?= $iconClass ?>"></i> <?php endif; ?><?= $label ?? '' ?>
</button>
