<?php
  $attributes = $attributes ?? [];
  $attributes['class'] = (array)($attributes['class'] ?? []);
  $attributes['class'][] = 'finna-tooltip-btn';
  $attributes['type'] = 'button';
  $attributes['data-toggle'] = 'tooltip';
  $attributes['data-html'] = 'true';
  $attributes['data-placement'] = $placement ?? 'bottom';
  $attributes['data-original-title'] = $content;
  if (empty($label)) {
    $attributes['aria-label'] = $ariaLabel;
  }
?>
<button<?= $this->attributes($attributes) ?>>
  <?php if ($iconClass): ?><i class="fa <?= $iconClass ?>"></i> <?php endif; ?><?= $label ?? '' ?>
</button>
