<?php
  $__attributes = $this->htmlAttributes($attributes ?? []);
  $__attributes->add('class', 'finna-tooltip-btn');
  $__attributes->set([
    'type' => 'button',
    'data-toggle' => 'tooltip',
    'data-html' => 'true',
    'data-placement' => $placement ?? 'bottom',
    'data-original-title' => $content ?? ''
  ]);
?>
<?= $this->render('components/molecules/buttons/finna-btn/finna-btn.phtml', [
    'ariaLabel' => $ariaLabel ?? null,
    'attributes' => $__attributes,
    'iconClass' => $iconClass ?? null,
    'label' => $label ?? null
  ]); ?>
