<?php
  $attributes = $attributes ?? [];
  $attributes['class'] = (array)($attributes['class'] ?? []);
  $attributes['class'][] = 'finna-tabs-nav';
  $attributes['aria-label'] = $ariaLabel;
  $navAttributes = ['class' => ['nav-tabs']];
  if (in_array('finna-tabs-nav-lg', $attributes['class'])) {
    $navAttributes['class'][] = 'finna-nav-lg';
  }
  $this->headScript()->appendFile('components/organisms/navigation/finna-tabs-nav/finna-tabs-nav.js');
?>
<nav<?= $this->attributes($attributes) ?>>
  <?= $this->render('components/molecules/navigation/finna-nav/finna-nav.phtml', [
      'attributes' => $navAttributes,
      'items' => $items,
      'renderChildren' => 'simple'
    ]); ?>
</nav>
