<?php
  $__attributes = $this->htmlAttributes($attributes ?? []);
  $__lowercase = $lowercase ?? true;
  $__listTag = isset($title) ? 'dl' : 'ul';
  $__itemTag = isset($title) ? 'dd' : 'li';
?>
<<?= $__listTag ?><?= $__attributes->add('class', 'finna-tag-list') ?>>
  <?php if (isset($title)): ?>
    <dt><?= $this->escapeHtml($title) ?></dt>
  <?php endif; ?>
  <?php foreach ($items ?? [] as $__item): ?>
    <?php $__item = $this->escapeHtml($__lowercase ? mb_strtolower($__item) : $__item); ?>
    <<?= $__itemTag ?>><?= $__item ?></<?= $__itemTag ?>>
  <?php endforeach; ?>
</<?= $__listTag?>>
