<!DOCTYPE html>
<html class="<?= $htmlClass ?? '' ?>">
  <head>
    <title><?= $title ?? '' ?></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width"/>

    <link rel="stylesheet" href="../../css/bootstrap.css?<?= $cacheBuster ?>" media="all"/>
    <link rel="stylesheet" href="../../css/vendor/fontawesome-free/all.min.css?<?= $cacheBuster ?>" media="all"/>
    <link rel="stylesheet" href="../../css/vendor/jquery-ui/jquery-ui.min.css?<?= $cacheBuster ?>" media="all"/>
    <link rel="stylesheet" href="../../css/components.css?<?= $cacheBuster ?>" media="all"/>

    <!-- Begin Pattern Lab (Required for Pattern Lab to run properly) -->
    <?= $patternLabHead ?>
    <!-- End Pattern Lab -->

  </head>
  <body class="<?= $bodyClass ?? '' ?>">
