<!DOCTYPE html>
<html class="<?= $htmlClass ?? '' ?>">
  <head>
    <title><?= $title ?? '' ?></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width"/>

    <!-- Dependencies from theme -->
    <link rel="stylesheet" href="../../css/styleguide/theme.css?<?= $cacheBuster ?>" media="all"/>

    <!-- Used in style guide only -->
    <link rel="stylesheet" href="../../css/styleguide/styleguide.css?<?= $cacheBuster ?>" media="all"/>

    <!-- Components -->
    <link rel="stylesheet" href="../../css/components.css?<?= $cacheBuster ?>" media="all"/>

    <!-- Component dependencies -->
    <link rel="stylesheet" href="../../css/vendor/easymde.min.css?<?= $cacheBuster ?>" media="all"/>

    <!-- Dependencies from theme -->
    <script src="../../js/styleguide/vendor/jquery.min.js?<?= $cacheBuster ?>"></script>
    <script src="../../js/styleguide/vendor/bootstrap.min.js?<?= $cacheBuster ?>"></script>

    <!-- Used in style guide only -->
    <script src="../../js/styleguide/vufind.js?<?= $cacheBuster ?>"></script>
    <script src="../../js/styleguide/finna.js?<?= $cacheBuster ?>"></script>
    <script src="../../js/styleguide/finna-layout.js?<?= $cacheBuster ?>"></script>
    <script src="../../js/styleguide/vendor/jquery.mockjax.min.js?<?= $cacheBuster ?>"></script>
    <script src="../../js/styleguide/mockjax.js?<?= $cacheBuster ?>"></script>

    <!-- Dependencies from theme -->
    <script src="../../js/styleguide/vendor/truncate.js?<?= $cacheBuster ?>"></script>

    <!-- Component dependencies -->
    <script src="../../js/vendor/easymde.min.js?<?= $cacheBuster ?>"></script>

    <!-- Begin Pattern Lab (Required for Pattern Lab to run properly) -->
    <?= $patternLabHead ?>
    <!-- End Pattern Lab -->

  </head>
  <body class="<?= $bodyClass ?? '' ?>">
